## Introduction To SciKit-Learn 
This notebook will walk you through some of the useful functions of Scikit-Learn Library.

What Are you going to Learn:

    1.An end to end  sklearn workflow
    2.getting the data ready
    3.choose the right estimator/algorithm for our problem
    4.Fit the model/algorithm and use it to make prediction on our data
    5.Evaluating a model
    6.Improve a model
    7.Save and load a trained model
    8.Putting it all together

## 0. And End-to-End Scikit-Learn workflow

In [2]:
#1. Get the data ready
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
heart_disease = pd.read_csv('43 - heart-disease.csv')
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [3]:
# Create X (Feature Matrix)
X = heart_disease.drop('target',axis=1)

#create Y(labels)
Y = heart_disease['target']


#Chose the right model and hyperparameter

from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# We will keep the defult hyperparameters

clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [4]:
# 3. Fit the model to the tranning data 

from sklearn.model_selection import train_test_split

x_train, x_test,y_train,y_test = train_test_split(X,Y, test_size=0.2)

clf.fit(x_train,y_train);

In [5]:
# Make Prediciton
x_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
190   51    0   0       130   305    0        1      142      1      1.2   
183   58    1   2       112   230    0        0      165      0      2.5   
64    58    1   2       140   211    1        0      165      0      0.0   
128   52    0   2       136   196    0        0      169      0      0.1   
10    54    1   0       140   239    0        1      160      0      1.2   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
73    51    1   0       140   261    0        0      186      1      0.0   
212   39    1   0       118   219    0        1      140      0      1.2   
93    54    0   1       132   288    1        0      159      1      0.0   
277   57    1   1       124   261    0        1      141      0      0.3   
240   70    1   2       160   269    0        1      112      1      2.9   

     slope  ca  thal  
190      1   0     3  
183      1   1     3  
64       2   0     2  
128      1   0     2  
10       2   0     2  
..     ...  ..   ...  
73       2   0     2  
212      1   0     3  
93       2   1     2  
277      2   0     3  
240      1   1     3  

[61 rows x 13 columns]

In [6]:
y_predc = clf.predict(x_test)
y_predc

array([0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0], dtype=int64)

In [7]:
y_test

190    0
183    0
64     1
128    1
10     1
      ..
73     1
212    0
93     1
277    0
240    0
Name: target, Length: 61, dtype: int64

In [8]:
# 4.Evaluate The model on the tranning data and testing data
clf.score(x_train,y_train)

1.0

In [9]:
clf.score(x_test,y_test)

0.8852459016393442

In [10]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test,y_predc))

              precision    recall  f1-score   support

           0       0.88      0.85      0.86        26
           1       0.89      0.91      0.90        35

    accuracy                           0.89        61
   macro avg       0.88      0.88      0.88        61
weighted avg       0.89      0.89      0.88        61



In [11]:
confusion_matrix(y_test, y_predc)

array([[22,  4],
       [ 3, 32]], dtype=int64)

In [12]:
accuracy_score(y_test,y_predc)

0.8852459016393442

In [13]:
# 5. Improve a model 
# Try Different amount of n_estimators
np.random.seed(42)
for i in range(10,100,10):
    print(f"Trying model with {i} estimators...")
    clf = RandomForestClassifier(n_estimators=i).fit(x_train,y_train)
    print(f"Model accuracy on test set:{clf.score(x_test,y_test)*100:.2f}%")
    print("")

Trying model with 10 estimators...
Model accuracy on test set:86.89%

Trying model with 20 estimators...
Model accuracy on test set:88.52%

Trying model with 30 estimators...
Model accuracy on test set:86.89%

Trying model with 40 estimators...
Model accuracy on test set:88.52%

Trying model with 50 estimators...
Model accuracy on test set:91.80%

Trying model with 60 estimators...
Model accuracy on test set:86.89%

Trying model with 70 estimators...
Model accuracy on test set:88.52%

Trying model with 80 estimators...
Model accuracy on test set:86.89%

Trying model with 90 estimators...
Model accuracy on test set:88.52%



In [14]:
 # 6. Save a model and load it
import pickle

pickle.dump(clf,open("random_forest_model_1.pkl","wb"))

In [15]:
loaded_model = pickle.load(open("random_forest_model_1.pkl",'rb'))
loaded_model.score(x_test,y_test)

0.8852459016393442

## 1. Getting our Data ready to be used with machine learning 

    Three main things we have to do:
        1. Split the data into features and labels (usually'x' and 'y')
        2. Filling (also called imputing) or disregarding missing values
        3. Converting non-numerical values to numerical values (also callled feature encoding)

In [16]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [17]:
x = heart_disease.drop('target',axis=1)
x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [18]:
y = heart_disease['target']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [19]:
# Split the data into tranning and test sets
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y, test_size = 0.2)

In [20]:
X_train.shape, X_test.shape,Y_train.shape,Y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [21]:
x.shape

(303, 13)

In [22]:
len(heart_disease)

303

## 1.1 Make Sure Its all numericals

In [24]:
car_sales = pd.read_csv('car-sales-extended.csv')
car_sales

Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [25]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [27]:
#Split the data into x/y 

x= car_sales.drop('Price', axis=1)
y= car_sales['Price']

# Split into tranning and testing datasets
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)


In [28]:
 # Build Machine learing model 
from sklearn.ensemble import RandomForestRegressor 

model = RandomForestRegressor()
model.fit(x_train,y_train)
model.score(x_test,y_test)

ValueError: could not convert string to float: 'Toyota'

In [30]:
# Trun the data into numerical data
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_feature = ['Make','Colour','Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',
                                one_hot,
                                categorical_feature)],
                               remainder = 'passthrough')
transformed_x = transformer.fit_transform(x)
transformed_x


array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [31]:
pd.DataFrame(transformed_x)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [32]:
dummies = pd.get_dummies(car_sales[['Make','Colour','Doors']])
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4         0           1            0            0             0   
1        5         1           0            0            0             0   
2        4         0           1            0            0             0   
3        4         0           0            0            1             0   
4        3         0           0            1            0             0   
..     ...       ...         ...          ...          ...           ...   
995      4         0           0            0            1             1   
996      3         0           0            1            0             0   
997      4         0           0            1            0             0   
998      4         0           1            0            0             0   
999      4         0           0            0            1             0   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0              0             0           0             1  
1              1             0           0             0  
2              0             0           0             1  
3              0             0           0             1  
4              1             0           0             0  
..           ...           ...         ...           ...  
995            0             0           0             0  
996            0             0           0             1  
997            1             0           0             0  
998            0             0           0             1  
999            1             0           0             0  

[1000 rows x 10 columns]

In [33]:
# Let's refit the model
np.random.seed(42)
x_train,x_test,y_train,y_test = train_test_split(transformed_x,y,test_size=0.2)
model.fit(x_train,y_train)

RandomForestRegressor()

In [34]:
model.score(x_test,y_test)

0.3235867221569877

## 2. What if There was missing values ?
    1.Fill them with some values(also known as imputation)
    2.Remove the sample with the missing data altogether
    

In [38]:
car_sales_missing = pd.read_csv('car-sales-extended-missing-data.csv')
car_sales_missing.head(20)

Make Colour  Odometer (KM)  Doors    Price
0    Honda  White        35431.0    4.0  15323.0
1      BMW   Blue       192714.0    5.0  19943.0
2    Honda  White        84714.0    4.0  28343.0
3   Toyota  White       154365.0    4.0  13434.0
4   Nissan   Blue       181577.0    3.0  14043.0
5    Honda    Red        42652.0    4.0  23883.0
6   Toyota   Blue       163453.0    4.0   8473.0
7    Honda  White            NaN    4.0  20306.0
8      NaN  White       130538.0    4.0   9374.0
9    Honda   Blue        51029.0    4.0  26683.0
10  Nissan  White       167421.0    4.0  16259.0
11  Nissan  Green        17119.0    4.0   6160.0
12  Nissan  White       102303.0    4.0  16909.0
13     NaN  White       134181.0    4.0  11121.0
14   Honda   Blue       199833.0    4.0  18946.0
15  Toyota   Blue       205592.0    4.0  16290.0
16  Toyota    Red        96742.0    4.0  34465.0
17     BMW  White       194189.0    5.0  17177.0
18  Nissan  White        67991.0    3.0   9109.0
19  Nissan   Blue       215820.0    4.0   6010.0

In [40]:
car_sales_missing.isnull().sum()


Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

## !! Fill missing data  with pandas

In [46]:
# Fill the Make Column 
car_sales_missing['Make'].fillna("missing",inplace=True)
# Fill the "Colour" Column
car_sales_missing['Colour'].fillna("missing",inplace=True)
# Fill the "Odometer (KM)" column
car_sales_missing['Odometer (KM)'].fillna(car_sales_missing['Odometer (KM)'].mean(),inplace= True)
#Fill the 'Doors' Column
car_sales_missing['Doors'].fillna(4,inplace=True)

In [53]:
# Remove 'price' rows with missing values
car_sales_missing.dropna(inplace=True)

In [54]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [60]:
# Split our datta into  x and y 
x = car_sales_missing.drop('Price',axis=1)
y = car_sales_missing['Price']

In [61]:
# lets try and convert our data to numbers
#Turn the categories into numbers

categorical_feature = ['Make','Colour','Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',
                                one_hot,
                                categorical_feature)],
                               remainder = 'passthrough')
transformed_x = transformer.fit_transform(car_sales_missing)
transformed_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

In [58]:
np.random.seed(42)
x_train,x_test,y_train,y_test = train_test_split(transformed_x,y,test_size=0.2)
model.fit(x_train,y_train)

RandomForestRegressor()

In [59]:
model.score(x_test,y_test)

0.22011714008302485

## Fill missing values with scikit-learn