In [39]:
import numpy as np 

## Data Type and Attribute

In [40]:
#NumPy's main dataType is ndarry
a1 = np.array([1,2,3,4,5,6,7,8])
a1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
type(a1)

numpy.ndarray

In [42]:
a2 = np.array([[1,2.0,3.3],
              [4,5,6.4]])
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [43]:

a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [44]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.4]])

In [45]:
a1.shape

(8,)

In [46]:
a2.shape

(2, 3)

In [47]:
a2.ndim

2

In [48]:
a3.ndim

3

In [49]:
type(a2)

numpy.ndarray

In [50]:
# Create a Dataframe for NumPy Array
import pandas as pd 
df = pd.DataFrame(a2)

In [51]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.4

In [52]:
one = np.ones((2,3))
one


array([[1., 1., 1.],
       [1., 1., 1.]])

In [53]:
zero = np.zeros((3,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [55]:
random_array = np.random.randint(10,size =(3,3))
random_array

array([[2, 0, 1],
       [8, 8, 3],
       [2, 4, 9]])

In [56]:
# pseudo-random number
np.random.seed(seed = 999999)
ramdom_array_4 = np.random.randint(10,size = (5,3))
ramdom_array_4

array([[1, 7, 4],
       [6, 9, 6],
       [1, 1, 0],
       [3, 0, 6],
       [4, 7, 3]])

In [57]:
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.2131054 , 0.64358082, 0.45169251],
       [0.09857734, 0.51496664, 0.04321696],
       [0.06179466, 0.43786989, 0.20075976],
       [0.34510067, 0.82669436, 0.43052215],
       [0.10510928, 0.15929179, 0.70400492]])

## Viewing Array and Matrices 

In [58]:
 np.unique(ramdom_array_4)

array([0, 1, 3, 4, 6, 7, 9])

In [59]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
a1[0]

1

In [61]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.4]])

In [62]:
a2[1]

array([4. , 5. , 6.4])

In [63]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [64]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [65]:
a4 = np.random.randint(10,size = (2,3,4,5))
a4

array([[[[1, 7, 5, 9, 1],
         [8, 9, 0, 2, 3],
         [5, 4, 0, 9, 0],
         [6, 6, 0, 6, 2]],

        [[8, 2, 2, 1, 2],
         [7, 7, 1, 9, 8],
         [5, 6, 8, 6, 4],
         [9, 8, 1, 1, 9]],

        [[0, 1, 5, 2, 1],
         [0, 0, 3, 8, 3],
         [0, 8, 4, 1, 5],
         [5, 1, 9, 6, 5]]],


       [[[8, 8, 4, 9, 2],
         [8, 6, 3, 1, 8],
         [1, 5, 5, 3, 2],
         [9, 2, 7, 8, 2]],

        [[9, 7, 8, 1, 6],
         [0, 6, 6, 8, 7],
         [8, 5, 2, 1, 4],
         [6, 2, 5, 2, 9]],

        [[5, 7, 9, 5, 7],
         [0, 2, 3, 4, 1],
         [5, 6, 1, 7, 3],
         [7, 4, 0, 9, 7]]]])

In [66]:
a4.shape ,a4.ndim

((2, 3, 4, 5), 4)

In [67]:
a4[:,:,:,:4]

array([[[[1, 7, 5, 9],
         [8, 9, 0, 2],
         [5, 4, 0, 9],
         [6, 6, 0, 6]],

        [[8, 2, 2, 1],
         [7, 7, 1, 9],
         [5, 6, 8, 6],
         [9, 8, 1, 1]],

        [[0, 1, 5, 2],
         [0, 0, 3, 8],
         [0, 8, 4, 1],
         [5, 1, 9, 6]]],


       [[[8, 8, 4, 9],
         [8, 6, 3, 1],
         [1, 5, 5, 3],
         [9, 2, 7, 8]],

        [[9, 7, 8, 1],
         [0, 6, 6, 8],
         [8, 5, 2, 1],
         [6, 2, 5, 2]],

        [[5, 7, 9, 5],
         [0, 2, 3, 4],
         [5, 6, 1, 7],
         [7, 4, 0, 9]]]])

In [68]:
a4[:,:,:,:1]

array([[[[1],
         [8],
         [5],
         [6]],

        [[8],
         [7],
         [5],
         [9]],

        [[0],
         [0],
         [0],
         [5]]],


       [[[8],
         [8],
         [1],
         [9]],

        [[9],
         [0],
         [8],
         [6]],

        [[5],
         [0],
         [5],
         [7]]]])

## Manipulating and comparing arrays

### Arithmetics

In [69]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
ones = np.ones(8)
ones

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [71]:
a1 + ones

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [72]:
a1 - ones

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [73]:
a1 * ones 

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [74]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.4]])

In [75]:
a0 = np.array([2,3,4])
a0

array([2, 3, 4])

In [76]:
a0*a2

array([[ 2. ,  6. , 13.2],
       [ 8. , 15. , 25.6]])

## Aggretation  
Aggretation is performing the same operation on a number of things

In [77]:
listy_list = [1,2,3]
type(listy_list)

list

In [78]:
sum(listy_list)

6

Use Python methods (sum()) on Python datatypes and use NumPy methods in Numpy array (np.sum()).

In [82]:
# create a massive NumPy array 

massive_array = np.random.random(100000)
massive_array.size

100000

In [83]:
massive_array[:10]

array([0.0166983 , 0.83717204, 0.54771861, 0.96164253, 0.19560444,
       0.10244742, 0.51891965, 0.10299562, 0.09319371, 0.7739343 ])

In [84]:
%timeit sum(massive_array) #Python sum()
%timeit np.sum(massive_array) # NumPy sum()

8.27 ms ± 54.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
31.7 µs ± 120 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [85]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.4]])

In [87]:
np.mean(a2)

3.616666666666667

In [88]:
np.max(a2)

6.4

In [89]:
np.min(a2)

1.0

In [90]:
np.std(a2)

1.7966790352078905

In [91]:
np.var(a2)

3.228055555555556

In [92]:
np.sqrt(a2)

array([[1.        , 1.41421356, 1.81659021],
       [2.        , 2.23606798, 2.52982213]])

In [93]:
np.sqrt(np.var(a2))

1.7966790352078905

### RESHAPING  AND TRANSPOSING 

In [94]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [95]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.4]])

In [96]:
a3.shape

(2, 3, 3)

In [97]:
a2.shape

(2, 3)

In [98]:
a2_reshape = a2.reshape(2,3,1)

In [100]:
a2_reshape*a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [102.4, 108.8, 115.2]]])

In [104]:
#transpose 
a2.shape

(2, 3)

In [106]:
a2.T.shape

(3, 2)

In [105]:
a2.shape

(2, 3)

## Dot product Example (nut butter sales)

In [108]:
np.random.seed(0)
#number of jars sold
sales_amount = np.random.randint(20, size =(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [109]:
weeekly_sales = pd.DataFrame(sales_amount,
                            index=["Mon","Tues","Wed","Thus","Fri"],
                            columns=["Almond Butter","Peanut Butter", "Cashew Butter"])
weeekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thus              4              6             12
Fri               1              6              7

In [110]:
#create the price array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [112]:
#create butter_price DataFrame
butter_price = pd.DataFrame(prices.reshape(1,3),
                           index=["Price"],
                           columns=["Almond Butter","Peanut Butter", "Cashew Butter"])
butter_price

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [113]:
# Shape are not alligned , lests  transpose
total_sales = prices.dot(sales_amount.T)
total_sales

array([240, 138, 458, 232, 142])

In [114]:
# Create Daily sales 
butter_price

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [115]:
butter_price.shape , weeekly_sales.shape

((1, 3), (5, 3))

In [116]:
daily_sales = butter_price.dot(weeekly_sales.T)
daily_sales

Mon  Tues  Wed  Thus  Fri
Price  240   138  458   232  142

In [117]:
weeekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thus              4              6             12
Fri               1              6              7

In [120]:
#
weeekly_sales["Total $"] = daily_sales.T
weeekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total $
Mon              12             15              0      240
Tues              3              3              7      138
Wed               9             19             18      458
Thus              4              6             12      232
Fri               1              6              7      142

## Comparasion Operators

In [121]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [122]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.4]])

In [123]:
a0

array([2, 3, 4])

In [124]:
a0>a2

array([[ True,  True,  True],
       [False, False, False]])

In [125]:
a0>=a2

array([[ True,  True,  True],
       [False, False, False]])

## Sorting Array

In [128]:
random_array = np.random.randint(10, size = (3,5))
random_array

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2]])

In [129]:
random_array.shape

(3, 5)

In [130]:
np.sort(random_array)

array([[1, 3, 3, 3, 8],
       [0, 1, 7, 9, 9],
       [0, 2, 3, 4, 7]])

In [131]:
np.argsort(random_array)

array([[1, 2, 3, 4, 0],
       [1, 2, 0, 3, 4],
       [0, 4, 3, 1, 2]], dtype=int64)

In [132]:
a0

array([2, 3, 4])

In [133]:
np.argsort(a0)

array([0, 1, 2], dtype=int64)

In [134]:
np.argmin(a0)

0

In [135]:
np.argmax(a0)

2

In [136]:
random_array

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2]])

In [138]:
np.argmax(random_array, axis=0)

array([0, 2, 2, 1, 1], dtype=int64)

In [139]:
np.argmax(random_array, axis=1)

array([0, 3, 2], dtype=int64)

## Pratical Example - NumPy in Action!!!!

<img src="panda.png"/>

In [143]:
# turn Image into a NumPy Array 

from matplotlib.image import imread

pandas = imread("panda.png")
print(type(pandas))

<class 'numpy.ndarray'>


In [146]:
pandas.size , pandas.dtype

(24465000, dtype('float32'))

In [148]:
pandas.shape

(2330, 3500, 3)

<img src= "Indian user data .png"/>

In [149]:
dataIndida = imread("Indian user data .png") 

In [150]:
dataIndida.shape

(465, 572, 4)

In [151]:
dataIndida

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       ...,

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1.